name: package-fn-app
variables:
  - template: global.yml
  - name: resourceGroupName
    value: 'rg-mbe-test-ks'
trigger: none

steps:
  - script: |
      dotnet restore
      dotnet build --configuration Release
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--configuration Release --output publish_output'
      projects: '*.csproj'
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
      artifactName: 'drop'

  - task: AzureFunctionApp@2 # Add this at the end of your file
    inputs:
      connectedServiceNameARM: 'rusmith-sandbox'
      appType: 'functionApp'
      appName: 'fnapp-mbefnclient-Dev-Client-dev'
      package: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
      deploymentMethod: 'zipDeploy'
      #slotName: '<Slot name>'  
  - task: AzureFunctionApp@2 # Add this at the end of your file
    inputs:
      azureSubscription: rusmith-sandbox
      appType: functionApp # default is functionApp
      appName: 'fnapp-mbefnclient-SIT-Client-dev'
      package: $(System.ArtifactsDirectory)/**/*.zip
      #Uncomment the next lines to deploy to a deployment slot
      #Note that deployment slots is not supported for Linux Dynamic SKU
      #deployToSlotOrASE: true
      resourceGroupName: '$(resourceGroupName)'
      deploymentMethod: 'zipDeploy'
      #slotName: '<Slot name>'
  - task: AzureFunctionApp@2 # Add this at the end of your file
    inputs:
      azureSubscription: rusmith-sandbox
      appType: functionApp # default is functionApp
      appName: 'fnapp-mbefnclient-PreProd-Client-dev'
      package: $(System.ArtifactsDirectory)/**/*.zip
      #Uncomment the next lines to deploy to a deployment slot
      #Note that deployment slots is not supported for Linux Dynamic SKU
      #deployToSlotOrASE: true
      resourceGroupName: '$(resourceGroupName)'
      deploymentMethod: 'zipDeploy'
      #slotName: '<Slot name>'
  - task: AzureFunctionApp@2 # Add this at the end of your file
    inputs:
      azureSubscription: rusmith-sandbox
      appType: functionApp # default is functionApp
      appName: 'fnapp-mbefnclient-Prod-Client-dev'
      package: $(System.ArtifactsDirectory)/**/*.zip
      #Uncomment the next lines to deploy to a deployment slot
      #Note that deployment slots is not supported for Linux Dynamic SKU
      #deployToSlotOrASE: true
      resourceGroupName: '$(resourceGroupName)'
      deploymentMethod: 'zipDeploy'
      #slotName: '<Slot name>'
  - task: AzureFunctionApp@2 # Add this at the end of your file
    inputs:
      connectedServiceNameARM: 'rusmith-sandbox'
      appType: 'functionApp'
      appName: 'fnapp-mbefnclient-DR-Client-dev'
      package: '$(System.ArtifactsDirectory)/**/*.zip'
      deploymentMethod: 'zipDeploy'
      #slotName: '<Slot name>