name: package-fn-app
variables:
  - template: global.yml
  - name: resourceGroupName
    value: 'rg-mbe-test-ks'
trigger: none

steps:
  - script: |
      dotnet restore
      dotnet build --configuration Release
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--configuration Release --output publish_output'
      projects: '*.csproj'
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
      artifactName: 'drop'
  - task: AzureFunctionApp@2 # Add this at the end of your file
    inputs:
      connectedServiceNameARM: 'rusmith-sandbox'
      appType: 'functionApp'
      appName: 'fnapp-mbefnclient-Dev-Client-dev'
      package: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
      deploymentMethod: 'zipDeploy'

